wandb_version: 1

bagging_fraction:
  value: 0.456673830516136
feature_fraction:
  value: 0.7340662376272721
learning_rate:
  value: 0.0838069012359525
min_child_samples:
  value: 36
min_data_in_leaf:
  value: 572
num_leaves:
  value: 179
