wandb_version: 1

bagging_fraction:
  value: 0.567460339444923
feature_fraction:
  value: 0.694487085646343
learning_rate:
  value: 0.0913508972335106
min_child_samples:
  value: 97
min_data_in_leaf:
  value: 4853
num_leaves:
  value: 24
