wandb_version: 1

bagging_fraction:
  value: 0.961054980238338
feature_fraction:
  value: 0.7314295056591391
learning_rate:
  value: 0.0864629813510148
min_child_samples:
  value: 56
min_data_in_leaf:
  value: 1240
num_leaves:
  value: 45
