wandb_version: 1

bagging_fraction:
  value: 0.7873624134793785
feature_fraction:
  value: 0.9715874299462844
learning_rate:
  value: 0.0919237971812074
min_child_samples:
  value: 5
min_data_in_leaf:
  value: 3808
num_leaves:
  value: 37
