wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.18.3
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731545396
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 54
      - 55
      3:
      - 23
      4: 3.11.1
      5: 0.18.3
      8:
      - 5
      13: darwin-arm64
average_unc_cutoff:
  desc: null
  value: 0.021153365369091855
bagging_fraction:
  desc: null
  value: 0.4020318837690579
feature_fraction:
  desc: null
  value: 0.6557703361901037
learning_rate:
  desc: null
  value: 0.006149369982245644
min_child_samples:
  desc: null
  value: 69
min_data_in_leaf:
  desc: null
  value: 2658
num_leaves:
  desc: null
  value: 168
