wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.18.3
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731536377
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 54
      - 55
      3:
      - 23
      4: 3.11.1
      5: 0.18.3
      8:
      - 5
      13: darwin-arm64
average_unc_cutoff:
  desc: null
  value: 0.04058612636623209
bagging_fraction:
  desc: null
  value: 0.5639255791455584
feature_fraction:
  desc: null
  value: 0.4281014905329889
learning_rate:
  desc: null
  value: 0.02945306408367715
min_child_samples:
  desc: null
  value: 55
min_data_in_leaf:
  desc: null
  value: 2250
num_leaves:
  desc: null
  value: 235
