wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.18.3
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731530615
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 54
      - 55
      3:
      - 23
      4: 3.11.1
      5: 0.18.3
      8:
      - 5
      13: darwin-arm64
average_unc_cutoff:
  desc: null
  value: 0.021091674791785517
bagging_fraction:
  desc: null
  value: 0.7115539088406235
feature_fraction:
  desc: null
  value: 0.7178742333162433
learning_rate:
  desc: null
  value: 0.005311138289019197
min_child_samples:
  desc: null
  value: 23
min_data_in_leaf:
  desc: null
  value: 3487
num_leaves:
  desc: null
  value: 114
