wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.18.3
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731540746
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 54
      - 55
      3:
      - 23
      4: 3.11.1
      5: 0.18.3
      8:
      - 5
      13: darwin-arm64
average_unc_cutoff:
  desc: null
  value: 0.022356404636860058
bagging_fraction:
  desc: null
  value: 0.8116110450471201
feature_fraction:
  desc: null
  value: 0.472433007886386
learning_rate:
  desc: null
  value: 0.011441173343604252
min_child_samples:
  desc: null
  value: 44
min_data_in_leaf:
  desc: null
  value: 1244
num_leaves:
  desc: null
  value: 225
