wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.18.3
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731580262
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 54
      - 55
      3:
      - 23
      4: 3.11.1
      5: 0.18.3
      8:
      - 5
      13: darwin-arm64
bagging_fraction:
  desc: null
  value: 0.7662759361468748
feature_fraction:
  desc: null
  value: 0.5717552562819839
learning_rate:
  desc: null
  value: 0.07501490803729284
min_child_samples:
  desc: null
  value: 87
min_data_in_leaf:
  desc: null
  value: 3210
num_leaves:
  desc: null
  value: 43
