wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.18.3
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731542655
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 54
      - 55
      3:
      - 23
      4: 3.11.1
      5: 0.18.3
      8:
      - 5
      13: darwin-arm64
average_unc_cutoff:
  desc: null
  value: 0.014866199703316206
bagging_fraction:
  desc: null
  value: 0.40103942706641926
feature_fraction:
  desc: null
  value: 0.937799042730426
learning_rate:
  desc: null
  value: 0.0459674889235475
min_child_samples:
  desc: null
  value: 53
min_data_in_leaf:
  desc: null
  value: 524
num_leaves:
  desc: null
  value: 81
